test/gas.js
This commit adds tests for the gas usage of eth-multisig-v4
CLOSES TICKET: BG-30043
=> Add Gas check test to eth-multisig-v4

.solcover.js, contracts/WalletSimple.sol, contracts/test/MockERC721.sol, package-lock.json, package.json, test/walletsimple.js
BG-38848
https://bitgoinc.atlassian.net/browse/BG-38848
The purpose of this PR is to support ERC721 token send and receive for WalletSimple contract.We will send ERC721 token via sendMultiSig function with data payload.I have added unit tests for this.
=> ERC721 token unit tests for wallet simple

contracts/ERC721Interface.sol, contracts/Forwarder.sol, contracts/WalletSimple.sol, test/forwarder.js, test/walletsimple.js
Ticket: BG-39779 https://bitgoinc.atlassian.net/browse/BG-39779
The Scope of the ticket is to add units for forwarder/wallet to support ERC721 token transfer.
=> feat(forwarder): unitTests for NFT Fowarder

ABIs/Forwarder.json, ABIs/README.md, contracts/ForwarderFactory.sol, test/forwarderFactory.js
ticket: [BG-40430](https://bitgoinc.atlassian.net/browse/BG-40430)
=> feat(forwarder): accept flush params for ERC721 tokens

contracts/Forwarder.sol, test/forwarder.js
ticket: [BG-39595](https://bitgoinc.atlassian.net/browse/BG-39595)
=> feat(forwarder): toggle autoflush721 params

contracts/Forwarder.sol, contracts/test/MockERC1155.sol, package-lock.json, package.json, test/forwarder.js
=> feat(forwarder): ERC1155Receiver implementation

contracts/WalletSimple.sol, test/walletsimple.js
=> feat(wallet): support IERC1155Receiver

contracts/Forwarder.sol, contracts/WalletSimple.sol, test/forwarder.js, test/walletsimple.js
=> fix(forwarder): add eip1155 token flushing

contracts/Forwarder.sol, contracts/WalletSimple.sol, test/forwarder.js, test/walletsimple.js
=> feat(forwarder): add eip1555 batch token flushing

.solcover.js, contracts/test/ReentryForwarder.sol, contracts/test/ReentryWalletSimple.sol, test/forwarder.js, test/walletsimple.js
Ticket: BG-40294 https://bitgoinc.atlassian.net/browse/BG-40294
=> feat(ethMultiSig): add re-entrancy tests

.solhint.json
=> chore: update solhint to use single quotes

contracts/Forwarder.sol, contracts/ForwarderFactory.sol, contracts/WalletSimple.sol, test/forwarderFactory.js, test/gas.js
Run `npm run prettier` and `npm run prettier:solidity` on project.
ticket: BG-40593
=> chore: format project

contracts/Forwarder.sol, contracts/IForwarder.sol, contracts/WalletSimple.sol, test/forwarder.js
=> feat: ERC165 support for forwarder

contracts/WalletSimple.sol, test/walletsimple.js
=> fix: add toggle erc721 and erc1155 methods to wallet

.solhint.json, contracts/Batcher.sol, contracts/CloneFactory.sol, contracts/ERC20Interface.sol, contracts/Forwarder.sol, contracts/ForwarderFactory.sol, contracts/TransferHelper.sol, contracts/WalletFactory.sol, contracts/WalletSimple.sol, contracts/coins/CeloWalletSimple.sol, contracts/coins/EtcWalletSimple.sol, contracts/coins/RskWalletSimple.sol, contracts/test/AlwaysFalseERC165.sol, contracts/test/Fail.sol, contracts/test/FixedSupplyToken.sol, contracts/test/ForwarderTarget.sol, contracts/test/GasGuzzler.sol, contracts/test/GasHeavy.sol, contracts/test/MockERC1155.sol, contracts/test/MockERC721.sol, contracts/test/Reentry.sol, contracts/test/ReentryForwarder.sol, contracts/test/ReentryWalletSimple.sol, contracts/test/TestBatcherDriver.sol, contracts/test/Tether.sol, truffle.js
=> chore: upgrade to solidity 0.8.10

contracts/Forwarder.sol, contracts/IForwarder.sol, contracts/WalletSimple.sol
=> fix: documentation

test/batcher.js, test/gas.js
Ticket: BG-40737 https://bitgoinc.atlassian.net/browse/BG-40737
=> fix(gas): fix gas tests

contracts/Forwarder.sol, contracts/WalletSimple.sol
- Removes unnecessary IForwarder checks since we own the contracts
- Removes unnecessary re-entrancy guards
=> Address Barath J's Audit Feedback feedback

.prettierignore, test/walletSimple.js
Decrease expireTime value so it fails during test as expected
Add typechain to prettier ignore as its generated in the container for lint step
Ticket: BG-46843
=> fix: lint failing on typechain and flaky unit test in CI

.github/workflows/deploy_and_release.yml, .github/workflows/push.yml
=> CI : add github action workflow for deploying the smart contracts

scripts/deploy.ts
=> chore: fix lint

README.md
Updated Readme to include the step of adding .env file and p…rivate key
=> BG-48243 Updated Readme

hardhat.config.ts
ticket: https://bitgoinc.atlassian.net/browse/BG-50294
passed all unit tests
=> chore: add polygon networks

scripts/deploy.ts
=> feat: add wallet contract switch based on chain

contracts/recoveryContracts/RecoveryWalletFactory.sol, contracts/recoveryContracts/RecoveryWalletSimple.sol, test/wallet/helpers.js, test/walletFactory.js, test/walletSimple.js
This PR adds recovery wallet contract to help with cross chain recovery for evm like chains which allows to move funds using single sig
=> feat(contracts): add recovery contracts for v1/v2 wallets versions

.github/workflows/deploy_and_release.yml, hardhat.config.ts, scripts/deploy.ts
=> feat(bsc): add config for deployment

CODEOWNERS
=> chore(codeowners) : Add codeowners to secure github actions

.github/renovate.json
=> chore: use nodejs-security preset for renovate

CODEOWNERS
=> chore: update codeowners to use production team

contracts/ForwarderFactory.sol
ForwarderFactory createForwarder's previous comment referred to signers, which aren't applicable here.
=> Fix comment in ForwarderFactory createForwarder

scripts/deploy.ts
This PR updates the deployment script to use the legacy transaction gas params.
WIN-1131
=> chore(eth-multisig-v4): update contract deployment script

hardhat.config.ts, scripts/deploy.ts
This PR makes changes to deploy v2 contracts on polygon amoy testnet
WIN-2821
=> feat(eth-multisig-v4): deploy polygon amoy test contracts

scripts/deploy.ts
=> feat(deploy): update script to deploy v4 contracts on holesky

hardhat.config.ts
=> chore(config): deploy v4 contracts on eth mainnet

hardhat.config.ts
=> feat: deploy v2 contracts on opt and arb prod

scripts/deployV1FactoryContracts.ts
=> fix(deploy): make use of current nonce to deploy contracts

hardhat.config.ts, scripts/deployBatcherContract.ts
Ticket: COIN-956
- add deployment script for batcher contract
- update config for eth url
=> feat(script): add script to deploy batcher contract

hardhat.config.ts, scripts/deploy.ts
=> chore(deploy): deploy v2 recovery contracts on bsc

scripts/deploy.ts
Ticket: COIN-1296
We already have V4 multisig contracts deployed on bsc so planning to use multig as well for v2
https://bscscan.com/address/0x944FEF03Af368414F29dC31a72061B8D64F568d2#code
=> fix(deploy): use v2  multiSig contracts for bsc

.github/workflows/deploy_and_release.yml, .github/workflows/push.yml
=> chore(wth-multisig-v4): add base config

scripts/deploy.ts
=> feat(eth-multisig-v4): update contract deploy script to use eip1559

scripts/deploy.ts
=> fix(eth-multisig-v4): fix switch case by adding break

.github/workflows/deploy_and_release.yml, package.json
=> chore(eth-multisig-v4): add deploy batcher smart contract in workflow

.github/workflows/deploy_and_release.yml, package.json
Reverts BitGo/eth-multisig-v4#164
=> Revert "chore(eth-multisig-v4): add deploy batcher smart contract in workflow"

hardhat.config.ts, scripts/deploy.ts
=> feat(contract): deploy base v4 contract

hardhat.config.ts, package.json
=> feat(contract): deploy base v1 contract

.github/workflows/deploy_and_release.yml
=> chore(eth-multisig-v4): add bera config

package.json
=> feat(deploy): v1 contracts on arb sepolia

hardhat.config.ts, package.json, scripts/deploy.ts
Ticket: COIN-1593
Update script to deploy only forwarder contracts based on nonce
=> feat(script): update to deploy script

hardhat.config.ts
=> chore: update arbeth url

hardhat.config.ts, package.json
=> chore: deploy v1 contracts for arb chain

.github/workflows/deploy_and_release.yml, hardhat.config.ts, scripts/deploy.ts
=> feat: support avaxc coin

hardhat.config.ts, package.json, scripts/deploy.ts
=> chore: update script to deploy v4 contracts

scripts/deploy.ts
=> chore(ccr): use default gas params

hardhat.config.ts
=> chore: fix avaxc typo

.github/workflows/deploy_batcher_contract.yml
Ticket: [WIN-3863](https://bitgoinc.atlassian.net/browse/WIN-3863)
[WIN-3863]: https://bitgoinc.atlassian.net/browse/WIN-3863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(eth-multisig-v4): add oas, coredao config in deploy_batcher_contract

.github/workflows/deploy_batcher_contract.yml
=> feat: updating deploy batcher workflow to run on-demand rather than on-release

hardhat.config.ts
=> chore(eth-multisig-v4): get bera secrete key from git secrets

hardhat.config.ts, scripts/deploy.ts
=> chore(eth-multisig-v4): adding the new coredao testnet

contracts/Batcher.sol, contracts/test/BlacklistedToken.sol, scripts/deployBatcherContract.ts, test/batcher.js
Ticket: COIN-2782
This is a follow up PR of https://github.com/BitGo/eth-multisig-v4/pull/192
=> chore: add test for token with blacklisted address

scripts/deployBatcherContract.ts
=> fix: updating verify batcher contract arguments

hardhat.config.ts, scripts/deployBatcherContract.ts
=> fix: updating hardhat config to get correct key in deploy batcher script

hardhat.config.ts, scripts/deployBatcherContract.ts
=> fix: update fee for deploying batcher in coredao testnet. updated xdc api & explorer endpoints

hardhat.config.ts
=> fix: updating coredao testnet api endpoint

contracts/Batcher.sol, contracts/test/Reentry.sol, scripts/deployBatcherContract.ts, test/batcher.js
Ticket: COIN-3589
This PR addresses the following points.
- BBG-04
- BBG-05
- BBG-06
- BBG-07
- BBG-08
- BBG-01
=> chore: address audit comment for batcher

hardhat.config.ts
=> fix: use intended key for batcher deployment on tbera

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml, .github/workflows/push.yml, hardhat.config.ts, scripts/deploy.ts
=> chore(eth-multisig-v4): add soneium config for contract deployment

hardhat.config.ts
=> fix: use intended key for batcher deployment

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml, .github/workflows/push.yml, hardhat.config.ts, scripts/deploy.ts
=> chore(eth-multisig-v4): add world config for contract deployment

scripts/deployBatcherContract.ts
=> fix: script to nativeBatchLimit for verifying

hardhat.config.ts, scripts/deploy.ts, scripts/deployBatcherContract.ts, yarn.lock
=> chore: add verify contract script

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml, deployUtils.ts, hardhat.config.ts, package.json, yarn.lock
This pull request updates the Node.js version used across workflows and the project, enhances the contract verification process, and replaces a Hardhat plugin with an updated alternative. Below are the most important changes grouped by theme:
**Reference Document**
https://docs.etherscan.io/etherscan-v2/contract-verification/verify-with-hardhat
* Updated the Node.js version from `16.x` to `18.x` in the following GitHub Actions workflows: `.github/workflows/deploy_and_release.yml` (`deploy-test` and `deploy-prod` jobs) [[1]](diffhunk://#diff-34aebd83955317a1e57b564cd5bb9e70b53cd59d094e606641eaed46efa5aac0L85-R85) [[2]](diffhunk://#diff-34aebd83955317a1e57b564cd5bb9e70b53cd59d094e606641eaed46efa5aac0L166-R166) and `.github/workflows/deploy_batcher_contract.yml` (`deploy-batcher` job) …
=> chore: upgrade hardhat to take advantage of verify:verify for etherscan v2

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml, .github/workflows/push.yml, hardhat.config.ts, scripts/chainConfig.ts
=> chore(eth-multisig-v4): add seievm config for contract deployment

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml, .github/workflows/push.yml, hardhat.config.ts, scripts/chainConfig.ts
=> chore(eth-multisig-v4): add hypeevm config for contract deployment

hardhat.config.ts, scripts/chainConfig.ts
=> feat(deploy): update script to deploy v2 contracts on hoodi hteth

hardhat.config.ts, package.json
=> chore: hoodi v1 contract deployment

hardhat.config.ts, package.json, scripts/chainConfig.ts
Ticket: COIN-4849
Tested this locally.
Contract Creator: https://hoodi.etherscan.io/address/0x83a436910cf145ad0362be19493a3880d3cd26ac
WalletSimple: https://hoodi.etherscan.io/address/0xdb53a55c2dd72b955fc2a1a7df590e9cd8a56108#code
WalletFactory: https://hoodi.etherscan.io/address/0x77fdcdc47276ed298bccf71948b785af078a91be#code 
ForwarderV4: https://hoodi.etherscan.io/address/0x27606731a0f3186ab13266a8c076a520c7bc72c1#code
ForwarderFactoryV4: https://hoodi.etherscan.io/address/0xe7c1bcdc932acc06820c6619608c2757e44e3cf0#code
=> feat(contract): deploy hoodi v4 contract

.github/workflows/deploy_and_release.yml, README.md, config/bigBlocksConfig.ts, package.json, scripts/deploy.ts, scripts/enableBigBlocks.ts, scripts/secp256k1Wrapper.ts, yarn.lock
=> feat: added script to enable bigBlocks for hypeEVM

hardhat.config.ts
=> fix: update IRYS testnet RPC URLs in hardhat configuration

.github/workflows/deploy_and_release.yml, .github/workflows/deploy_batcher_contract.yml
=> chore: added the summary for approval

hardhat.config.ts
=> chore: changing the private key for contract deployment

deployUtils.ts, scripts/deploy.ts, scripts/deployBatcherContract.ts
=> chore: enforced the funds before contract deployment
