- contracts/Forwarder.sol
- contracts/WalletSimple.sol
- contracts/test/Tether.sol
- package-lock.json
- package.json
- test/walletsimple.js
Some ERC20 token contracts don't return boolean from their transfer
function. We were previously requiring the return value from transfer
calls to be true, throwing otherwise. This commit uses the uniswap
TransferHelper library to safely send tokens while handling cases both
where the token returns a boolean and where it doesn't.
> Fix for ERC20 tokens that don't return boolean

- contracts/Batcher.sol
- mocha-test/compile.js
- test/batcher.js
- test/forwarder.js
- test/forwarderFactory.js
- test/helpers.js
- test/walletFactory.js
- test/walletsimple.js
- testrpc/accounts.js
- testrpc/run.js
Remove sending back stuck funds in batcher
Currently, sending extra funds to batcher will send all funds that are
in the batcher contract to msg.sender. We replace this action by
letting an admin call the recover function to remove stuck funds.
This is done to prevent someone from front running a transaction
that leaves ETH in the contract and calling batch() right after to
withdraw the contract balance.
CLOSES Ticket: BG-28164
> Remove sending extra funds to sender

- contracts/Batcher.sol
This commit fixes the contract comment for batcher to correctly specify
that any excess ETH sent to the contract will remain stuck.
This is in response to smart contract audit request L-3.3.1
> Fix Batcher Comment

- contracts/WalletSimple.sol
- test/gas.js
Sload is a very expensive operation in ethereum - it costs 800 gas each
time. In the tryInsertSequenceId function we perform many sloads to
fetch the values of sequence ids at different locations in the array.
This commit improves the gas utilization of this function by only
fetching the values from storage one time, reading them from memory
after that.
CLOSES TICKET: BG-30046
> Read sequence id array from memory

- .solcover.js
- package-lock.json
- package.json
- test/gas.js
- test/walletsimple.js
- truffle.js
This commits adds test coverage for solidity files using solidity-coverage. Solidity-coverage adds additional gas for certain function calls so the gas-related tests are skipped. This PR also adds test cases for flushing 0 balance tokens in `Forwarder.sol`. 
Coverage can be run with `npm run coverage`
> Add solidity-coverage

- package-lock.json
- package.json
- test/walletsimple.js
This PR bumps the ganache-cli version to work with node-14, adds truffle-flatener for easy contract deploys using remix, and adds a new Tether test for wallet simple.
> Add Tether test for WalletSimple

- contracts/Forwarder.sol
- contracts/TransferHelper.sol
- contracts/WalletSimple.sol
- package-lock.json
- package.json
Removes the external uniswap dependency since we only rely on 2 of their functions.
ticket: BG-40975
> chore: remove uniswap library

- contracts/Forwarder.sol
- contracts/WalletSimple.sol
- contracts/test/AlwaysFalseERC165.sol
Changes the modifier to external to align with the contract interface.
ticket: BG-40980
> fix: onERC721Received function signature to use external

- ABIs/Forwarder.json
- contracts/Forwarder.sol
- contracts/IForwarder.sol
- contracts/WalletSimple.sol
- test/forwarder.js
Address the following issues found during the audit
```
(M-1) `flushERC721Tokens` overly restrictive
Forwarder.sol’s `flushERC721Tokens` reverts unless the forwarder is the owner of the token, or if it’s approved for that specific token. However, this logic reverts even if the forwarder is an **operator** of the token’s owner via ERC-721’s `setApprovalForAll` function.
Consider removing these checks and defering validation to `transferFrom`.
(M-2) Unused Parameter
In Forwarder.sol’s `onERC721Received` function, `instance.safeTransferFrom` does not use the `_data` parameter like `onERC1155Received` does. Consider passing this through so no intended behavior is lost.
```
```
Nitpicks
- There’s a whitespace change in `tryInsertSequenceId`. Consider taking that out of the diff.
- …
```
> fix: address minor audit fixes

- ABIs/Forwarder.json
- contracts/Forwarder.sol
- contracts/IForwarder.sol
- contracts/TransferHelper.sol
- contracts/WalletSimple.sol
- test/forwarder.js
- test/walletsimple.js
Fixes the following issues
```
(L-1) Forwarder cannot receive tokens in edge case
Both Forwarder’s `callFromParent` and receive callbacks (`onERC721Received`, etc) have the `nonReentrant` modifier. Because of this, any function call made through `callFromParent` will prevent the Forwarder from receiving any ERC-721 and ERC-1155 tokens.
Consider removing `nonReentrant` from the receive callbacks.
(L-2) Toggle functions race condition
`toggleAutoFlush721` and `toggleAutoFlush1155` are vulnerable to a user-based race condition. If two signers Alice and Bob independently decide – in parallel – to toggle *on* an auto flush, their two transactions will cancel each other out, leaving the auto flush *off*.
Consider updating these functions to be idempotent by accepting a `boolean` parameter, …
```
> fix: address medium audit fixes

- contracts/coins/MaticLWalletSimple.sol
- test/walletSimple.js
This commit adds support for MaticL. The main change for this chain is that the operation hash prefix must be specific to the chain, to avoid cross-chain replay attacks. For example, on ETH chain it is the
string "ETHER", on POLYGON chain it is the string "MATICL".
[BG-43071](https://bitgoinc.atlassian.net/browse/BG-43071)
> feat(ethmultisig): add maticl support

- contracts/Batcher.sol
- test/batcher.js
> Batcher’s recovery function does not verify call success. Contracts calling this function
might expect the transaction to fail if the call was not successful
89 function recover(
90 address to,
91 uint256 value,
92 bytes calldata data
93 ) external onlyOwner returns (bytes memory) {
94 (bool success, bytes memory returnData) = to.call{ value: value }(data);↤
95 return returnData;
96 }
Recommendation
Require transaction success
Fixes the above audit issue.
ticket: BG-43313
> fix: missing require success statement in batcher recover calls

- contracts/Forwarder.sol
> Description
Data returned by transactions is ignored, greatly limiting wallet functionality.
contracts/WalletSimple.sol
210 (bool success, ) = toAddress.call{ value: valu.e }(data);↤
The Forwarder callFromParent function ignores the returned call data and returns
the data parameter instead.
contracts/Forwarder.sol
134 function callFromParent(
135 address target,
136 uint256 value,
137 bytes calldata data
138 ) external onlyParent returns (bytes calldata) {
139 (bool success, ) = target.call{ value: value }(data);↤
140 require(success, 'Parent call execution failed');
141 return data;↤
142 }
Recommendation
Consider returning calls returned data.
Fixes the above audit issue.
ticket: BG-43312
> fix: call from parent returned call data

- scripts/deploy.ts
Add 5 min wait to ensure etherscan backend picks up the tx and contract deployment.
> fix: add wait in deploy script before verify

- contracts/coins/PolygonWalletSimple.sol
- test/walletSimple.js
This commit adds support for Polygon. The main change for this chain is that the operation hash prefix must be specific to the chain, to avoid cross-chain replay attacks. For example, on ETH chain it is the
string "ETHER", on POLYGON chain it is the string "POLYGON".
[BG-43071](https://bitgoinc.atlassian.net/browse/BG-43071)
> feat(eth-multisig-v4): add polygon support

- contracts/coins/ArbethWalletSimple.sol
- contracts/coins/OpethWalletSimple.sol
- test/gas.js
- test/walletSimple.js
This PR adds support for Arbeth and Opeth. The main change for these chains is that the operation hash prefix must be specific to the chain, to avoid cross-chain replay attacks. For example, on ETH chain it is the
string "ETHER", on Arbitrum chain it is the string "ARBETH", and on Optimism chain it is "OPETH".
WIN-1013
> feat(eth-multisig-v4): add arbeth and opeth wallet contract

- .github/workflows/deploy_and_release.yml
- .github/workflows/push.yml
- hardhat.config.ts
- scripts/deploy.ts
> chore(eth-multisig-v4): add arbeth and opeth config

- contracts/WalletSimple.sol
- contracts/coins/ArbethWalletSimple.sol
- contracts/coins/OpethWalletSimple.sol
- test/gas.js
- test/walletFactory.js
- test/walletSimple.js
This PR updates getNetworkId(), getTokenNetworkId(), getBatchNetworkId() methods to return the chain id as the network identifier for WalletSimple, ArbethWalletSimple and OpethWalletSimple contracts.
> Win 1423 update v4 contracts arbeth opeth

- README.md
- contracts/ForwarderFactoryV4.sol
- contracts/ForwarderV4.sol
- contracts/IForwarderV4.sol
- test/forwarderFactoryV4.js
- test/forwarderV4.js
- test/gas.js
This PR adds 3 contracts ForwarderV4.sol, ForwarderFactoryV4.sol and IForwarderV4.sol
Change in contracts (as compared to Forwarder.sol and ForwarderFactory.sol) is that we have added feeAddress as an address that will be one of the allowed addresses to call the methods of the contract along with parentAddress. This means the methods to flush the tokens, etc can be called using the gas tank address. Apart from this batchFlushERC20Tokens method to batch flush erc20 tokens has been added to the ForwarderV4 contract
WIN-506
> feat(contracts): add new forwarder contracts

- .github/workflows/deploy_and_release.yml
- .github/workflows/push.yml
- contracts/coins/ZkethWalletSimple.sol
- hardhat.config.ts
- scripts/deploy.ts
This [commit](https://github.com/BitGo/eth-multisig-v4/pull/115/commits/353ad46b5b881f69de7ee4033c215ae7b376ffc7) adds the multisig wallet for zkSync.
This [commit](https://github.com/BitGo/eth-multisig-v4/pull/115/commits/e6be5f9f104beeaec3362d74a96c769587496fc5) updates the config for zkSync.
> Zksync wallet

- contracts/Batcher.sol
- contracts/Forwarder.sol
- contracts/ForwarderFactory.sol
- contracts/ForwarderFactoryV4.sol
- contracts/ForwarderV4.sol
- contracts/TransferHelper.sol
- contracts/WalletFactory.sol
- contracts/WalletSimple.sol
- contracts/recoveryContracts/RecoveryWalletFactory.sol
- contracts/recoveryContracts/RecoveryWalletSimple.sol
- contracts/test/MockERC1155.sol
- contracts/test/ReentryForwarder.sol
- hardhat.config.ts
- package.json
- test/batcher.js
- test/forwarder.js
- test/forwarderV4.js
- test/gas.js
- test/helpers.js
- test/walletFactory.js
- test/walletSimple.js
- yarn.lock
Commit 1: [fix BGB-03](https://github.com/BitGo/eth-multisig-v4/pull/120/commits/a8706b6e073b5644e228e55bdc85ef4b780cf0d2)
Commit 2: [fix RSC-02](https://github.com/BitGo/eth-multisig-v4/pull/120/commits/9305ad59b949b6cf73df1454413041dedbbb70da)
Commit 3: [fix BGB-02](https://github.com/BitGo/eth-multisig-v4/pull/120/commits/ccad0a378319485183c7e013afe23835fd65f2fe)
Commit 4: [fix GLOBAL-01](https://github.com/BitGo/eth-multisig-v4/pull/120/commits/c663442d2e47849c0010a77c0340dde2c13c9671) In this commit ERC1155Receiver contract was removed because it got depreciated in openzeppelin/contracts version 5.0.0. Instead ERC1155Holder contract is used for the same purpose.  The visibility of onERC1155Received and onERC1155BatchReceived method is changed to public because ERC1155Holder contract …
> address audit feedback

- package.json
- yarn.lock
This version should help us upgrading a transitive dependency on "flat" v4x
> chore(deps): upgrade hardhat-gas-reporter

- hardhat.config.ts
- scripts/deploy.ts
this pr adds changes to deploy v4 contracts
for bsc and polygon testnets
Ticket: WP-1803
> chore: deploy v4 contracts for polygon and bsc

- hardhat.config.ts
- scripts/deploy.ts
> feat(deploy): update script to deploy v2 contracts on topeth

- hardhat.config.ts
- scripts/deploy.ts
> feat(config): support base chain

- hardhat.config.ts
- package.json
- scripts/deploy.ts
> feat(base): deploy v2 contracts on base chain

- .github/workflows/deploy_and_release.yml
- .github/workflows/push.yml
- hardhat.config.ts
- scripts/deploy.ts
> chore(eth-multisig-v4): add oas, coredao config

- .github/workflows/deploy_and_release.yml
- .github/workflows/deploy_batcher_contract.yml
Ticket: [WIN-4036](https://bitgoinc.atlassian.net/browse/WIN-4036)
[WIN-4036]: https://bitgoinc.atlassian.net/browse/WIN-4036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: updating regex in the deploy github actions

- .github/workflows/deploy_and_release.yml
- .github/workflows/deploy_batcher_contract.yml
- .github/workflows/push.yml
- hardhat.config.ts
- scripts/deploy.ts
- scripts/deployBatcherContract.ts
Ticket: WIN-4221
Deployed contracts locally on personal address:
https://testnet.wemixscan.com/address/0xbcb86416188235942990EA10c8D72e34170e7F18
> chore(eth-multisig-v4): add wemix config for contract deployment

- contracts/Batcher.sol
- test/batcher.js
> feat: modify batcher contract to support erc20 sendMany

- hardhat.config.ts
Ticket: COIN-3587
This PR intends to add key (PRIVATE_KEY_FOR_BATCHER_CONTRACT_DEPLOYMENT) for deploying batcher contract.
this was not present for EVM chains, probably because the new [workflow](https://github.com/BitGo/eth-multisig-v4/actions/workflows/deploy_batcher_contract.yml) was added in Sep 2024 [here](https://github.com/BitGo/eth-multisig-v4/pull/167).
The old way of deploying a batcher contract was via release.
Going forward, we need to update hardhat.config for chains where we intend to deploy updated batcher contract.
> fix: update key for batcher deployment

- hardhat.config.ts
- scripts/chainConfig.ts
This pull request updates the configuration to replace references to the Ethereum Holesky testnet with the Ethereum Hoodi testnet across several files. The changes include modifications to URLs, chain IDs, and network names in the configuration and chain-handling logic.
* [`hardhat.config.ts`]: Updated the RPC URL for the `hteth` network from Holesky to Hoodi (`https://ethereum-hoodi-rpc.publicnode.com`).
* [`hardhat.config.ts`]: Changed the custom chain configuration to use the Hoodi network name, chain ID `560048`, and updated the corresponding API and browser URLs.
* [`scripts/chainConfig.ts`]: Replaced the Holesky chain ID `17000` with Hoodi chain ID `560048` in the `getChainConfig` function to ensure proper handling of the Hoodi network.
Ticket: COIN-4802
> feat: add hoodi configs
